# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bidirectional_pb2 as bidirectional__pb2


class BidirectionalServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BidirectionalStream = channel.stream_stream(
                '/grpc.BidirectionalServer/BidirectionalStream',
                request_serializer=bidirectional__pb2.Message.SerializeToString,
                response_deserializer=bidirectional__pb2.Message.FromString,
                )


class BidirectionalServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BidirectionalStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BidirectionalServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStream,
                    request_deserializer=bidirectional__pb2.Message.FromString,
                    response_serializer=bidirectional__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.BidirectionalServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BidirectionalServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BidirectionalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/grpc.BidirectionalServer/BidirectionalStream',
            bidirectional__pb2.Message.SerializeToString,
            bidirectional__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
